from __future__ import annotations

from collections.abc import Iterable
from math import factorial
from typing import TypeAlias

from symbolica import Expression, Replacement, S

from ..expr import as_int, is_head, list_expr, list_items, pow_parts, product_expr, sum_expr, terms
from ..logging import get_logger
from ..symbols import canonical_string, s
from . import vakint

LoopFunctionPower: TypeAlias = Expression | int
_LOGGER = get_logger("backends.vacuum_integrals")


def epsilon_symbol() -> Expression:
    """Return the dimensional regulator used by pychete's vacuum-integral series."""

    return S("vakint::ε")


def mu_r_squared_symbol() -> Expression:
    """Return the renormalization-scale-squared symbol used in vacuum-integral series."""

    return S("vakint::mursq")


def imaginary_unit_symbol() -> Expression:
    """Return the native Symbolica imaginary unit used by pychete results."""

    return Expression.I


def loop_function(masses: tuple[Expression, ...], powers: tuple[LoopFunctionPower, ...]) -> Expression:
    """Return pychete's Matchete-style finite loop-function placeholder.

    The convention mirrors Matchete's ``LF[{m1, ...}, {i1, ..., alpha}]``:
    ``masses`` are masses rather than mass-squared slots, ``powers[:-1]`` are
    massive propagator powers, and ``powers[-1]`` is the massless
    ``1/k^2`` power generated by numerator reduction.
    """

    power_exprs = tuple(_power_expression(power) for power in powers)
    _validate_loop_function_lengths(masses, power_exprs)
    return s.LoopFunction(list_expr(*masses), list_expr(*power_exprs))


def canonize_loop_function(expr: Expression) -> Expression:
    """Canonize one pychete ``LoopFunction`` atom.

    This mirrors Matchete's local ``LF`` atom normalization: repeated masses
    have their massive propagator powers summed, zero massive powers are
    removed, and remaining massive propagators are ordered by descending power
    and then by canonical mass name. The final massless ``1/k^2`` power is
    preserved. Purely scaleless massless remnants canonize to zero.
    """

    masses, powers = _loop_function_data(expr)
    alpha = powers[-1]
    mass_powers = _canonized_mass_powers(zip(masses, powers[:-1], strict=True))
    if not mass_powers:
        return Expression.num(0)
    return loop_function(
        tuple(mass for mass, _power in mass_powers),
        (*tuple(power for _mass, power in mass_powers), alpha),
    )


def canonize_loop_functions(expr: Expression, *, combine_terms: bool = False) -> Expression:
    """Canonize all pychete ``LoopFunction`` atoms in an expression.

    Replacement is delegated to Symbolica's native wildcard matcher. When
    ``combine_terms`` is set, the resulting expression is passed through
    ``Expression.together()`` so rational coefficients multiplying canonized
    loop functions can combine deterministically.
    """

    pattern = _loop_function_pattern()
    for match in expr.match(pattern):
        _loop_function_data(pattern.replace_wildcards(match))

    def canonize_match(match: dict[Expression, Expression]) -> Expression:
        return canonize_loop_function(pattern.replace_wildcards(match))

    return _finish_evaluated_expression(
        expr.replace(pattern, canonize_match).expand(),
        combine_terms=combine_terms,
    )


def loop_function_pole_part(
    expr: Expression,
    *,
    epsilon: Expression | None = None,
    max_pole_order: int = 1,
) -> Expression:
    """Return the epsilon pole part associated with one finite ``LoopFunction`` atom.

    Matchete's loop-function IBP identities are derived for full loop
    functions. When reducing finite ``LF`` placeholders, the epsilon-suppressed
    pieces generated by IBP can multiply pole terms and leave finite remnants.
    This helper extracts those pole terms from pychete's internal analytic
    one-loop evaluator using Symbolica coefficient extraction.
    """

    loop_expr = canonize_loop_function(expr)
    if bool(loop_expr == Expression.num(0)):
        return Expression.num(0)
    integral = loop_function_to_vakint_integral(loop_expr)
    evaluated = evaluate_one_loop_vakint_expression(
        integral,
        epsilon=epsilon,
        combine_terms=False,
    )
    return vakint.pole_part(
        (evaluated / imaginary_unit_symbol()).expand(),
        epsilon=epsilon,
        max_pole_order=max_pole_order,
    )


def reduce_loop_function_first_power(
    expr: Expression,
    *,
    target_mass_index: int = 0,
    epsilon: Expression | None = None,
    max_pole_order: int = 1,
    max_steps: int = 100,
) -> Expression:
    """Reduce one ``LoopFunction`` atom so one selected massive power is one.

    This is a focused pychete counterpart of Matchete's ``SimpTempLFRules``:
    the selected massive propagator is moved into the first slot, the native
    Symbolica replacement engine applies the IBP rule until that first power is
    one, and the finite epsilon coefficient is extracted after inserting the
    needed loop-function pole pieces. Broader mass-function optimization across
    sums is intentionally left to later matching slices.
    """

    loop_expr = canonize_loop_function(expr)
    if bool(loop_expr == Expression.num(0)):
        return Expression.num(0)
    masses, powers = _loop_function_data(loop_expr)
    if not 0 <= target_mass_index < len(masses):
        raise ValueError("target_mass_index is out of range for LoopFunction masses")
    if len(masses) < 2 or powers[target_mass_index] <= 1:
        return loop_expr
    current = _swap_loop_function_masses(loop_expr, target_mass_index, 0)
    pattern = _loop_function_pattern()
    regulator = epsilon_symbol() if epsilon is None else epsilon
    for _step in range(max_steps):
        if not _has_reducible_first_loop_function_power(current):
            break
        current = current.replace(
            pattern,
            lambda match: _reduce_first_power_match(
                pattern.replace_wildcards(match),
                epsilon=regulator,
            ),
        ).expand()
    else:
        raise RuntimeError("LoopFunction first-power reduction did not converge")
    return canonize_loop_functions(
        _finite_loop_function_expression(
            current,
            epsilon=regulator,
            max_pole_order=max_pole_order,
        ),
        combine_terms=True,
    )


def reduce_loop_functions_first_power(
    expr: Expression,
    *,
    target_mass_index: int = 0,
    epsilon: Expression | None = None,
    max_pole_order: int = 1,
    combine_terms: bool = False,
) -> Expression:
    """Apply first-power ``LoopFunction`` IBP reduction to every matching atom."""

    pattern = _loop_function_pattern()
    for match in expr.match(pattern):
        _loop_function_data(pattern.replace_wildcards(match))

    def reduce_match(match: dict[Expression, Expression]) -> Expression:
        return reduce_loop_function_first_power(
            pattern.replace_wildcards(match),
            target_mass_index=target_mass_index,
            epsilon=epsilon,
            max_pole_order=max_pole_order,
        )

    return _finish_evaluated_expression(
        expr.replace(pattern, reduce_match).expand(),
        combine_terms=combine_terms,
    )


def reduce_loop_function_ibp(
    expr: Expression,
    *,
    target_mass_index: int = 0,
    epsilon: Expression | None = None,
    max_pole_order: int = 1,
    max_steps: int = 100,
) -> Expression:
    """Reduce one ``LoopFunction`` atom with pychete's focused IBP rules.

    This extends ``reduce_loop_function_first_power(...)`` with Matchete's two
    massless-propagator relations for first-power loop functions. It is still a
    local atom reducer, not the full Matchete ``SimplifyMassFunction`` optimizer
    across sums.
    """

    loop_expr = canonize_loop_function(expr)
    if bool(loop_expr == Expression.num(0)):
        return Expression.num(0)
    masses, _powers = _loop_function_data(loop_expr)
    if not 0 <= target_mass_index < len(masses):
        raise ValueError("target_mass_index is out of range for LoopFunction masses")
    current = _swap_loop_function_masses(loop_expr, target_mass_index, 0)
    pattern = _loop_function_pattern()
    regulator = epsilon_symbol() if epsilon is None else epsilon
    for _step in range(max_steps):
        if not _has_reducible_ibp_loop_function(current):
            break
        current = current.replace(
            pattern,
            lambda match: _reduce_ibp_match(
                pattern.replace_wildcards(match),
                epsilon=regulator,
            ),
        ).expand()
    else:
        raise RuntimeError("LoopFunction IBP reduction did not converge")
    return canonize_loop_functions(
        _finite_loop_function_expression(
            current,
            epsilon=regulator,
            max_pole_order=max_pole_order,
        ),
        combine_terms=True,
    )


def reduce_loop_functions_ibp(
    expr: Expression,
    *,
    target_mass_index: int = 0,
    epsilon: Expression | None = None,
    max_pole_order: int = 1,
    combine_terms: bool = False,
) -> Expression:
    """Apply focused ``LoopFunction`` IBP reduction to every matching atom."""

    pattern = _loop_function_pattern()
    for match in expr.match(pattern):
        _loop_function_data(pattern.replace_wildcards(match))

    def reduce_match(match: dict[Expression, Expression]) -> Expression:
        return reduce_loop_function_ibp(
            pattern.replace_wildcards(match),
            target_mass_index=target_mass_index,
            epsilon=epsilon,
            max_pole_order=max_pole_order,
        )

    return _finish_evaluated_expression(
        expr.replace(pattern, reduce_match).expand(),
        combine_terms=combine_terms,
    )


def simplify_loop_functions(
    expr: Expression,
    *,
    epsilon: Expression | None = None,
    max_pole_order: int = 1,
    combine_terms: bool = False,
) -> Expression:
    """Simplify finite ``LoopFunction`` sums with Matchete-style IBP trials.

    This is pychete's sum-level counterpart of Matchete's
    ``SimplifyMassFunction``. Loop functions are first put in a common
    mass-sorted form, then each distinct mass tuple is optimized by trying each
    mass as the first propagator in the first-power IBP rule. A trial is kept
    only when the expanded term count for that mass-function group does not
    grow. The symbolic rule application and epsilon-finite extraction are
    delegated to Symbolica replacement and coefficient primitives; Python only
    chooses among the finite set of candidate target masses.
    """

    current_terms = list(terms(_order_loop_functions_by_mass(expr).expand()))
    regulator = epsilon_symbol() if epsilon is None else epsilon
    for mass_tuple in _loop_function_mass_types(sum_expr(current_terms)):
        if len(mass_tuple) < 2:
            continue
        keep_terms: list[Expression] = []
        group_terms: list[Expression] = []
        for term in current_terms:
            if _contains_loop_function_masses(term, mass_tuple):
                group_terms.append(term)
            else:
                keep_terms.append(term)
        if len(group_terms) < 2:
            continue
        target_count = len(group_terms)
        accepted_terms = group_terms
        for target_index in range(len(mass_tuple)):
            candidate = _simplify_loop_function_group(
                group_terms,
                mass_tuple,
                target_index=target_index,
                epsilon=regulator,
                max_pole_order=max_pole_order,
            )
            candidate_terms = list(terms(candidate.expand()))
            if len(candidate_terms) > target_count:
                continue
            target_count = len(candidate_terms)
            accepted_terms = candidate_terms
        current_terms = keep_terms + accepted_terms
    return _finish_evaluated_expression(
        _order_loop_functions_by_mass(sum_expr(current_terms)).expand(),
        combine_terms=combine_terms,
    )


def loop_function_to_vakint_integral(expr: Expression) -> Expression:
    """Lower one pychete ``LoopFunction`` atom to an equivalent scalar topology."""

    masses, powers = _loop_function_data(expr)
    alpha = powers[-1]
    mass_squareds: list[Expression] = []
    prop_powers: list[int] = []
    for mass, power in zip(masses, powers[:-1], strict=True):
        if power == 0:
            continue
        if power < 0:
            raise ValueError("LoopFunction massive propagator powers must be nonnegative integers")
        mass_squareds.append(mass**2)
        prop_powers.append(power)
    if alpha:
        mass_squareds.append(Expression.num(0))
        prop_powers.append(alpha)
    return vakint.one_loop_vacuum_integral(Expression.num(1), tuple(mass_squareds), powers=tuple(prop_powers))


def evaluate_loop_functions(
    expr: Expression,
    *,
    epsilon: Expression | None = None,
    mu_r_squared: Expression | None = None,
    combine_terms: bool = False,
) -> Expression:
    """Evaluate pychete ``LoopFunction`` atoms with the internal analytic backend.

    This returns the finite, real Matchete-style loop function. Internally it
    lowers the placeholder to a scalar one-loop topology, uses the same
    pychete analytic evaluator as matching, strips the common vakint
    imaginary-unit convention, and extracts the epsilon-finite coefficient with
    Symbolica's native coefficient machinery.
    """

    pattern = _loop_function_pattern()
    for match in expr.match(pattern):
        _loop_function_data(pattern.replace_wildcards(match))

    def evaluate_loop_function(match: dict[Expression, Expression]) -> Expression:
        loop_expr = canonize_loop_function(pattern.replace_wildcards(match))
        if bool(loop_expr == Expression.num(0)):
            return Expression.num(0)
        integral = loop_function_to_vakint_integral(loop_expr)
        evaluated = evaluate_one_loop_vakint_expression(
            integral,
            epsilon=epsilon,
            mu_r_squared=mu_r_squared,
            combine_terms=False,
        )
        return vakint.finite_part((evaluated / imaginary_unit_symbol()).expand(), epsilon=epsilon)

    return _finish_evaluated_expression(
        expr.replace(pattern, evaluate_loop_function).expand(),
        combine_terms=combine_terms,
    )


def expand_loop_scale_log_ratios(
    expr: Expression,
    *,
    mu_r_squared: Expression | None = None,
) -> Expression:
    """Expand compact loop-scale logarithms for validation comparison.

    Matchete fixtures often keep scale logs as ``log(mu^2 / M^2)``, while
    pychete's analytic backend naturally emits ``log(mu^2) - 2 log(M)``.
    This comparison helper rewrites only logarithms whose numerator is the
    selected renormalization scale. It uses Symbolica's native pattern
    replacement machinery and is intentionally opt-in because logarithm
    splitting is branch-sensitive outside the positive mass-scale convention
    used by these one-loop validation expressions.
    """

    scale_squared = mu_r_squared_symbol() if mu_r_squared is None else mu_r_squared
    inverse_factor = S("pychete_loop_scale_inverse_factor_")
    pattern = (scale_squared * inverse_factor).log()

    def expand_scale_log(match: dict[Expression, Expression]) -> Expression:
        matched = pattern.replace_wildcards(match)
        parts = pow_parts(match[inverse_factor])
        if parts is None:
            return matched
        base, exponent = parts
        power = as_int(exponent)
        if power is None or power >= 0:
            return matched
        return (scale_squared.log() + power * base.log()).expand()

    return expr.replace(pattern, expand_scale_log, rhs_cache_size=0).expand()


def evaluate_one_loop_single_scale_vacuum_integral(
    numerator: Expression,
    mass: Expression,
    *,
    power: int = 1,
    epsilon: Expression | None = None,
    mu_r_squared: Expression | None = None,
) -> Expression:
    """Evaluate the one-loop single-scale massive tadpole through finite order.

    This is pychete's internal analytic expression for the scalar one-loop
    vacuum integral with one propagator of mass ``mass`` and integer
    propagator ``power``, in the same normalization convention used by vakint's
    default MSbar evaluation with ``number_of_terms_in_epsilon_expansion=2``.
    It returns the pole and finite terms. Mixed-scale and massless topologies
    are intentionally left to later Matchete-style integral-backend slices.
    """

    return evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared(
        numerator,
        mass**2,
        power=power,
        epsilon=epsilon,
        mu_r_squared=mu_r_squared,
    )


def evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared(
    numerator: Expression,
    mass_squared: Expression,
    *,
    power: int = 1,
    epsilon: Expression | None = None,
    mu_r_squared: Expression | None = None,
) -> Expression:
    """Evaluate a single-scale massive tadpole from a mass-squared slot.

    The input convention matches vakint's ``prop(..., mass_squared, power)``
    topology slots, so this helper is the internal analytic counterpart of
    native vakint evaluation after topology-independent tensor reduction.
    """

    if power < 1:
        raise ValueError("power must be at least 1")
    if bool(mass_squared == Expression.num(0)):
        raise ValueError("single-scale massive vacuum integrals require a nonzero mass")

    return _single_scale_integral_from_mass_squared(
        numerator,
        mass_squared,
        beta=power,
        alpha=0,
        epsilon=epsilon,
        mu_r_squared=mu_r_squared,
    ).expand()


def evaluate_one_loop_single_scale_vakint_expression(
    expr: Expression,
    *,
    epsilon: Expression | None = None,
    mu_r_squared: Expression | None = None,
    combine_terms: bool = False,
) -> Expression:
    """Evaluate single-scale massive one-loop ``vakint::topo`` factors.

    This replacement-based evaluator is intended for vakint expressions after
    tensor reduction, where numerator algebra has already been handled and the
    remaining scalar topology is a one-loop, single-mass, massive vacuum
    topology. Unsupported zero-mass or mixed-mass topologies raise
    ``ValueError`` instead of delegating to native vakint. When
    ``combine_terms`` is set, the evaluated result is passed through
    Symbolica's native ``Expression.together()`` to expose cancellations across
    finite sums of loop functions.
    """

    _LOGGER.info("evaluating single-scale one-loop vakint expression with pychete analytic backend")
    expr = vakint.collect_identical_propagators(expr)
    pattern = _topology_pattern()
    for match in expr.match(pattern):
        _single_scale_topology_data(pattern.replace_wildcards(match))

    def evaluate_topology(match: dict[Expression, Expression]) -> Expression:
        topology = pattern.replace_wildcards(match)
        mass_squared, power = _single_scale_topology_data(topology)
        return evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared(
            Expression.num(1),
            mass_squared,
            power=power,
            epsilon=epsilon,
            mu_r_squared=mu_r_squared,
        )

    return _finish_evaluated_expression(
        expr.replace(pattern, evaluate_topology).expand(),
        combine_terms=combine_terms,
    )


def evaluate_one_loop_vakint_expression(
    expr: Expression,
    *,
    epsilon: Expression | None = None,
    mu_r_squared: Expression | None = None,
    combine_terms: bool = False,
) -> Expression:
    """Evaluate scalar one-loop ``vakint::topo`` factors with pychete.

    This implements Matchete's one-loop vacuum-integral reduction formula:
    zero-mass propagators are treated as powers of ``1/k^2``, repeated
    nonzero masses are combined, and multiscale topologies are reduced to
    derivatives of single-scale massive integrals with respect to mass-squared
    variables. Tensor numerators should be reduced before this scalar
    evaluation stage; remaining scalar native vakint products
    ``k(loop, index)^(2 n)`` are absorbed as negative massless propagator
    powers. When ``combine_terms`` is set, the evaluated result is passed
    through Symbolica's native ``Expression.together()`` to expose
    cancellations across finite sums of loop functions.
    """

    _LOGGER.info("evaluating one-loop vakint expression with pychete analytic backend")
    expr = absorb_vakint_scalar_loop_momentum_numerators(expr)
    pattern = _topology_pattern()
    for match in expr.match(pattern):
        _topology_data(pattern.replace_wildcards(match))

    def evaluate_topology(match: dict[Expression, Expression]) -> Expression:
        topology = pattern.replace_wildcards(match)
        mass_powers, massless_power = _topology_data(topology)
        return _multi_scale_integral_from_mass_squareds(
            mass_powers,
            alpha=massless_power,
            epsilon=epsilon,
            mu_r_squared=mu_r_squared,
        )

    return _finish_evaluated_expression(
        expr.replace(pattern, evaluate_topology).expand(),
        combine_terms=combine_terms,
    )


def absorb_vakint_scalar_loop_momentum_numerators(expr: Expression) -> Expression:
    """Convert native vakint scalar loop-momentum products to topology powers.

    Native vakint tensor reduction can leave scalar numerator factors such as
    ``vakint::k(1, i)^2`` multiplying a ``vakint::topo(...)``. pychete's
    analytic one-loop evaluator already represents powers of ``k^2`` as
    negative powers of the massless ``1/k^2`` propagator. This helper bridges
    those two conventions with a Symbolica wildcard replacement.
    """

    pattern = _scalar_loop_momentum_topology_pattern()

    def absorb_match(match: dict[Expression, Expression]) -> Expression:
        matched = pattern.replace_wildcards(match)
        exponent = as_int(match[_scalar_loop_momentum_power_pattern()])
        if exponent is None or exponent % 2:
            return matched
        massless_power = -exponent // 2
        if massless_power == 0:
            return _topology_pattern().replace_wildcards(match)
        return vakint.symbol("topo")(
            match[_topology_factors_pattern()]
            * _absorbed_scalar_loop_momentum_propagator(
                match[_scalar_loop_momentum_loop_pattern()],
                massless_power,
            )
        )

    return vakint.collect_identical_propagators(expr.expand().replace(pattern, absorb_match, repeat=True))


def _finish_evaluated_expression(expr: Expression, *, combine_terms: bool) -> Expression:
    if combine_terms:
        return expr.together()
    return expr


def _power_expression(power: LoopFunctionPower) -> Expression:
    return power if isinstance(power, Expression) else Expression.num(power)


def _loop_function_data(expr: Expression) -> tuple[tuple[Expression, ...], tuple[int, ...]]:
    if not is_head(expr, s.LoopFunction) or len(expr) != 2:
        raise ValueError(f"expected a pychete LoopFunction expression")
    masses = list_items(expr[0])
    power_exprs = list_items(expr[1])
    _validate_loop_function_lengths(masses, power_exprs)
    powers: list[int] = []
    for power_expr in power_exprs:
        power = as_int(power_expr)
        if power is None:
            raise ValueError("LoopFunction powers must be integers")
        powers.append(power)
    for power in powers[:-1]:
        if power < 0:
            raise ValueError("LoopFunction massive propagator powers must be nonnegative integers")
    return masses, tuple(powers)


def _order_loop_functions_by_mass(expr: Expression) -> Expression:
    pattern = _loop_function_pattern()
    for match in expr.match(pattern):
        _loop_function_data(pattern.replace_wildcards(match))

    def order_match(match: dict[Expression, Expression]) -> Expression:
        return _order_loop_function_by_mass(pattern.replace_wildcards(match))

    return expr.replace(pattern, order_match)


def _order_loop_function_by_mass(expr: Expression) -> Expression:
    masses, powers = _loop_function_data(expr)
    alpha = powers[-1]
    mass_powers = _mass_ordered_powers(zip(masses, powers[:-1], strict=True))
    if not mass_powers:
        return Expression.num(0)
    return loop_function(
        tuple(mass for mass, _power in mass_powers),
        (*tuple(power for _mass, power in mass_powers), alpha),
    )


def _canonized_mass_powers(
    items: Iterable[tuple[Expression, int]],
) -> tuple[tuple[Expression, int], ...]:
    combined: list[tuple[Expression, int]] = []
    for mass, power in items:
        if power == 0:
            continue
        for index, (existing_mass, existing_power) in enumerate(combined):
            if bool(mass == existing_mass):
                combined[index] = (existing_mass, existing_power + power)
                break
        else:
            combined.append((mass, power))
    return tuple(
        sorted(
            combined,
            key=lambda item: (-item[1], canonical_string(item[0])),
        )
    )


def _mass_ordered_powers(
    items: Iterable[tuple[Expression, int]],
) -> tuple[tuple[Expression, int], ...]:
    combined: list[tuple[Expression, int]] = []
    for mass, power in items:
        if power == 0:
            continue
        for index, (existing_mass, existing_power) in enumerate(combined):
            if bool(mass == existing_mass):
                combined[index] = (existing_mass, existing_power + power)
                break
        else:
            combined.append((mass, power))
    return tuple(sorted(combined, key=lambda item: canonical_string(item[0])))


def _swap_loop_function_masses(expr: Expression, first_index: int, second_index: int) -> Expression:
    masses, powers = _loop_function_data(expr)
    if first_index == second_index:
        return expr
    mass_list = list(masses)
    power_list = list(powers)
    mass_list[first_index], mass_list[second_index] = mass_list[second_index], mass_list[first_index]
    power_list[first_index], power_list[second_index] = power_list[second_index], power_list[first_index]
    return loop_function(tuple(mass_list), tuple(power_list))


def _loop_function_mass_types(expr: Expression) -> tuple[tuple[Expression, ...], ...]:
    pattern = _loop_function_pattern()
    mass_types: list[tuple[Expression, ...]] = []
    for match in expr.match(pattern):
        masses, _powers = _loop_function_data(pattern.replace_wildcards(match))
        if any(_same_mass_tuple(masses, known) for known in mass_types):
            continue
        mass_types.append(masses)
    return tuple(sorted(mass_types, key=lambda masses: (-len(masses), tuple(canonical_string(m) for m in masses))))


def _same_mass_tuple(left: tuple[Expression, ...], right: tuple[Expression, ...]) -> bool:
    return len(left) == len(right) and all(bool(a == b) for a, b in zip(left, right, strict=True))


def _contains_loop_function_masses(expr: Expression, masses: tuple[Expression, ...]) -> bool:
    pattern = s.LoopFunction(list_expr(*masses), s.LoopFunctionPowersWildcard)
    return any(True for _match in expr.match(pattern))


def _simplify_loop_function_group(
    group_terms: list[Expression],
    mass_tuple: tuple[Expression, ...],
    *,
    target_index: int,
    epsilon: Expression,
    max_pole_order: int,
) -> Expression:
    permuted = sum_expr(
        _swap_loop_functions_with_masses(term, mass_tuple, target_index=target_index)
        for term in group_terms
    )
    reduced = _apply_first_power_ibp_until_fixed(permuted, epsilon=epsilon)
    return _finite_loop_function_expression(
        reduced,
        epsilon=epsilon,
        max_pole_order=max_pole_order,
    ).expand()


def _swap_loop_functions_with_masses(
    expr: Expression,
    masses: tuple[Expression, ...],
    *,
    target_index: int,
) -> Expression:
    pattern = s.LoopFunction(list_expr(*masses), s.LoopFunctionPowersWildcard)

    def swap_match(match: dict[Expression, Expression]) -> Expression:
        return _swap_loop_function_masses(
            pattern.replace_wildcards(match),
            target_index,
            0,
        )

    return expr.replace(pattern, swap_match)


def _apply_first_power_ibp_until_fixed(
    expr: Expression,
    *,
    epsilon: Expression,
    max_steps: int = 100,
) -> Expression:
    current = expr
    pattern = _loop_function_pattern()
    for _step in range(max_steps):
        if not _has_reducible_first_loop_function_power(current):
            return current
        current = current.replace(
            pattern,
            lambda match: _reduce_first_power_match(
                pattern.replace_wildcards(match),
                epsilon=epsilon,
            ),
        ).expand()
    raise RuntimeError("LoopFunction sum simplification did not converge")


def _has_reducible_first_loop_function_power(expr: Expression) -> bool:
    pattern = _loop_function_pattern()
    return any(
        _first_loop_function_power_is_reducible(pattern.replace_wildcards(match))
        for match in expr.match(pattern)
    )


def _first_loop_function_power_is_reducible(expr: Expression) -> bool:
    masses, powers = _loop_function_data(expr)
    return len(masses) >= 2 and powers[0] > 1


def _has_reducible_ibp_loop_function(expr: Expression) -> bool:
    pattern = _loop_function_pattern()
    return any(
        _loop_function_ibp_is_reducible(pattern.replace_wildcards(match))
        for match in expr.match(pattern)
    )


def _loop_function_ibp_is_reducible(expr: Expression) -> bool:
    return _first_loop_function_power_is_reducible(expr) or _massless_power_is_reducible(expr)


def _massless_power_is_reducible(expr: Expression) -> bool:
    masses, powers = _loop_function_data(expr)
    return bool(masses) and powers[0] == 1 and powers[-1] != 0


def _reduce_ibp_match(expr: Expression, *, epsilon: Expression) -> Expression:
    if _first_loop_function_power_is_reducible(expr):
        return _reduce_first_power_match(expr, epsilon=epsilon)
    if _massless_power_is_reducible(expr):
        return _reduce_massless_power_match(expr)
    return expr


def _reduce_first_power_match(expr: Expression, *, epsilon: Expression) -> Expression:
    if not _first_loop_function_power_is_reducible(expr):
        return expr
    masses, powers = _loop_function_data(expr)
    first = powers[0]
    mid = powers[1:-1]
    last = powers[-1]
    denominator = Expression.num(first - 1)
    reduced_first = first - 1
    terms = [
        (Expression.num(1) - epsilon - last)
        / denominator
        * loop_function(masses, (reduced_first, *mid, last + 1))
    ]
    for index, mid_power in enumerate(mid, start=1):
        if mid_power == 0:
            continue
        new_powers = [reduced_first, *mid, last]
        new_powers[index] += 1
        terms.append(
            -Expression.num(mid_power)
            / denominator
            * loop_function(masses, tuple(new_powers))
        )
    return sum_expr(terms)


def _reduce_massless_power_match(expr: Expression) -> Expression:
    if not _massless_power_is_reducible(expr):
        return expr
    masses, powers = _loop_function_data(expr)
    first_mass = masses[0]
    mid = powers[1:-1]
    last = powers[-1]
    reduced_masses = masses[1:]
    if last > 0:
        return (
            -loop_function(reduced_masses, (*mid, last)) / first_mass**2
            + loop_function(masses, (1, *mid, last - 1)) / first_mass**2
        )
    return (
        loop_function(reduced_masses, (*mid, last + 1))
        + first_mass**2 * loop_function(masses, (1, *mid, last + 1))
    )


def _finite_loop_function_expression(
    expr: Expression,
    *,
    epsilon: Expression,
    max_pole_order: int,
) -> Expression:
    pattern = _loop_function_pattern()

    def full_loop_function(match: dict[Expression, Expression]) -> Expression:
        loop_expr = pattern.replace_wildcards(match)
        return loop_expr + loop_function_pole_part(
            loop_expr,
            epsilon=epsilon,
            max_pole_order=max_pole_order,
        )

    return vakint.finite_part(
        expr.replace(pattern, full_loop_function).expand(),
        epsilon=epsilon,
    )


def _validate_loop_function_lengths(
    masses: tuple[Expression, ...],
    powers: tuple[Expression, ...],
) -> None:
    if len(powers) != len(masses) + 1:
        raise ValueError("LoopFunction powers must contain one massive power per mass plus the final massless power")


def _loop_function_pattern() -> Expression:
    return s.LoopFunction(s.LoopFunctionMassesWildcard, s.LoopFunctionPowersWildcard)


def _single_scale_integral_from_mass_squared(
    numerator: Expression,
    mass_squared: Expression,
    *,
    beta: int,
    alpha: int,
    epsilon: Expression | None = None,
    mu_r_squared: Expression | None = None,
) -> Expression:
    if beta < 1:
        return Expression.num(0)
    regulator = epsilon_symbol() if epsilon is None else epsilon
    scale_squared = mu_r_squared_symbol() if mu_r_squared is None else mu_r_squared
    normalization = imaginary_unit_symbol() * numerator / (16 * Expression.PI**2)
    prefactor = (
        normalization
        * _sign(alpha + beta)
        * mass_squared ** (2 - alpha - beta)
        / factorial(beta - 1)
    )
    log_ratio = scale_squared.log() - _mass_squared_log(mass_squared)

    if alpha >= 2:
        coefficient = -prefactor * _gamma_integer(alpha + beta - 2) * _sign(alpha - 2) / factorial(alpha - 2)
        finite_bracket = -_harmonic_number(alpha - 2) + log_ratio + 1 + _harmonic_number(alpha + beta - 3)
        return (coefficient * (Expression.num(1) / regulator + finite_bracket)).expand()

    if alpha + beta <= 2:
        coefficient = (
            prefactor
            * _gamma_integer(2 - alpha)
            * _sign(alpha + beta)
            / factorial(2 - alpha - beta)
        )
        finite_bracket = _harmonic_number(2 - alpha - beta) + log_ratio + 1 - _harmonic_number(1 - alpha)
        return (coefficient * (Expression.num(1) / regulator + finite_bracket)).expand()

    return (prefactor * _gamma_integer(2 - alpha) * _gamma_integer(alpha + beta - 2)).expand()


def _multi_scale_integral_from_mass_squareds(
    mass_powers: tuple[tuple[Expression, int], ...],
    *,
    alpha: int,
    epsilon: Expression | None = None,
    mu_r_squared: Expression | None = None,
) -> Expression:
    if not mass_powers:
        return Expression.num(0)
    if len(mass_powers) == 1:
        mass_squared, beta = mass_powers[0]
        return _single_scale_integral_from_mass_squared(
            Expression.num(1),
            mass_squared,
            beta=beta,
            alpha=alpha,
            epsilon=epsilon,
            mu_r_squared=mu_r_squared,
        )

    temp_masses = tuple(S(f"pychete_internal_mass_squared_{i}") for i, _entry in enumerate(mass_powers))
    replacements = [
        Replacement(temp_mass, mass_squared)
        for temp_mass, (mass_squared, _power) in zip(temp_masses, mass_powers, strict=True)
    ]
    terms: list[Expression] = []
    for i, (mass_squared, beta) in enumerate(mass_powers):
        other_indices = tuple(j for j in range(len(mass_powers)) if j != i)
        for derivative_order in range(beta):
            product = product_expr(
                (temp_masses[i] - temp_masses[j]) ** (-mass_powers[j][1])
                for j in other_indices
            )
            derivative = product
            for _ in range(derivative_order):
                derivative = derivative.derivative(temp_masses[i])
            derivative = derivative.replace_multiple(replacements).expand() / factorial(derivative_order)
            terms.append(
                _single_scale_integral_from_mass_squared(
                    Expression.num(1),
                    mass_squared,
                    beta=beta - derivative_order,
                    alpha=alpha,
                    epsilon=epsilon,
                    mu_r_squared=mu_r_squared,
                )
                * derivative
            )
    out = sum_expr(terms).expand()
    if _is_finite_multiscale(mass_powers, alpha):
        scale_squared = mu_r_squared_symbol() if mu_r_squared is None else mu_r_squared
        out = out.replace(scale_squared, mass_powers[0][0]).expand()
    return out


def _is_finite_multiscale(mass_powers: tuple[tuple[Expression, int], ...], alpha: int) -> bool:
    return sum(power for _mass, power in mass_powers) + alpha > 2 and alpha < 2


def _gamma_integer(n: int) -> Expression:
    if n < 1:
        raise ValueError("gamma argument must be a positive integer")
    return Expression.num(factorial(n - 1))


def _harmonic_number(n: int) -> Expression:
    if n < 1:
        return Expression.num(0)
    return sum_expr(Expression.num(1) / k for k in range(1, n + 1))


def _sign(power: int) -> int:
    return -1 if power % 2 else 1


def _mass_squared_log(mass_squared: Expression) -> Expression:
    parts = pow_parts(mass_squared)
    if parts is not None:
        base, exponent = parts
        if as_int(exponent) == 2:
            return 2 * base.log()
    return mass_squared.log()


def _single_scale_topology_data(topology_expr: Expression) -> tuple[Expression, int]:
    if not is_head(topology_expr, vakint.symbol("topo")) or len(topology_expr) != 1:
        raise ValueError("expected a vakint::topo(...) expression")
    mass_powers, massless_power = _topology_data(topology_expr)
    if massless_power:
        raise ValueError("massless propagators require pychete's multiscale integral evaluator")
    if not mass_powers:
        raise ValueError("expected a one-loop topology with at least one propagator")
    reference_mass, total_power = mass_powers[0]
    if bool(reference_mass == Expression.num(0)):
        raise ValueError("single-scale massive vacuum integrals require nonzero masses")
    for mass_squared, power in mass_powers[1:]:
        if bool(mass_squared == Expression.num(0)):
            raise ValueError("single-scale massive vacuum integrals require nonzero masses")
        if not bool(mass_squared == reference_mass):
            raise ValueError("mixed-mass topologies require pychete's later mixed-scale integral backend")
        total_power += power
    return reference_mass, total_power


def _topology_data(topology_expr: Expression) -> tuple[tuple[tuple[Expression, int], ...], int]:
    if not is_head(topology_expr, vakint.symbol("topo")) or len(topology_expr) != 1:
        raise ValueError("expected a vakint::topo(...) expression")
    massless_power = 0
    mass_powers: list[tuple[Expression, int]] = []
    for mass_squared, power in _topology_mass_powers(topology_expr):
        if bool(mass_squared == Expression.num(0)):
            massless_power += power
            continue
        if power < 1:
            raise ValueError("massive vakint propagator powers must be positive integers for internal evaluation")
        for index, (existing_mass, existing_power) in enumerate(mass_powers):
            if bool(mass_squared == existing_mass):
                mass_powers[index] = (existing_mass, existing_power + power)
                break
        else:
            mass_powers.append((mass_squared, power))
    return tuple(mass_powers), massless_power


def _topology_mass_powers(topology_expr: Expression) -> tuple[tuple[Expression, int], ...]:
    topology_expr = vakint.collect_identical_propagators(topology_expr)
    pattern = _propagator_pattern()
    mass_wildcard = _propagator_mass_pattern()
    power_wildcard = _propagator_power_pattern()
    mass_powers: list[tuple[Expression, int]] = []
    for match in topology_expr.match(pattern):
        power_expr = power_wildcard.replace_wildcards(match)
        power = as_int(power_expr)
        if power is None:
            raise ValueError("vakint propagator powers must be integers for internal evaluation")
        mass_powers.append((mass_wildcard.replace_wildcards(match), power))
    return tuple(mass_powers)


def _topology_pattern() -> Expression:
    return vakint.symbol("topo")(_topology_factors_pattern())


def _topology_factors_pattern() -> Expression:
    return S("pychete_vakint_topology_factors_")


def _scalar_loop_momentum_topology_pattern() -> Expression:
    return (
        vakint.symbol("k")(
            _scalar_loop_momentum_loop_pattern(),
            _scalar_loop_momentum_index_pattern(),
        )
        ** _scalar_loop_momentum_power_pattern()
        * _topology_pattern()
    )


def _scalar_loop_momentum_loop_pattern() -> Expression:
    return S("pychete_vakint_loop_momentum_loop_")


def _scalar_loop_momentum_index_pattern() -> Expression:
    return S("pychete_vakint_loop_momentum_index_")


def _scalar_loop_momentum_power_pattern() -> Expression:
    return S("pychete_vakint_loop_momentum_power_")


def _absorbed_scalar_loop_momentum_propagator(
    loop_id: Expression,
    power: int,
) -> Expression:
    return vakint.symbol("prop")(
        0,
        vakint.edge(),
        vakint.symbol("k")(loop_id),
        Expression.num(0),
        power,
    )


def _propagator_pattern() -> Expression:
    return vakint.symbol("prop")(
        S("pychete_vakint_prop_id_"),
        S("pychete_vakint_prop_edge_"),
        S("pychete_vakint_prop_momentum_"),
        S("pychete_vakint_prop_mass_squared_"),
        S("pychete_vakint_prop_power_"),
    )


def _propagator_mass_pattern() -> Expression:
    return S("pychete_vakint_prop_mass_squared_")


def _propagator_power_pattern() -> Expression:
    return S("pychete_vakint_prop_power_")


__all__ = [
    "canonize_loop_function",
    "canonize_loop_functions",
    "absorb_vakint_scalar_loop_momentum_numerators",
    "epsilon_symbol",
    "evaluate_loop_functions",
    "evaluate_one_loop_single_scale_vakint_expression",
    "evaluate_one_loop_single_scale_vacuum_integral",
    "evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared",
    "evaluate_one_loop_vakint_expression",
    "expand_loop_scale_log_ratios",
    "imaginary_unit_symbol",
    "loop_function",
    "loop_function_pole_part",
    "loop_function_to_vakint_integral",
    "mu_r_squared_symbol",
    "reduce_loop_function_first_power",
    "reduce_loop_function_ibp",
    "reduce_loop_functions_first_power",
    "reduce_loop_functions_ibp",
    "simplify_loop_functions",
]
