from __future__ import annotations

from .dimensions import infer_coupling_mass_dimensions
from .eft import operator_dimension, series_eft
from .functional import hermitian_conjugate
from .group_algebra import simplify_pychete_color
from .backends.vacuum_integrals import (
    absorb_vakint_scalar_loop_momentum_numerators,
    canonize_loop_function,
    canonize_loop_functions,
    evaluate_loop_functions,
    evaluate_one_loop_single_scale_vakint_expression,
    evaluate_one_loop_single_scale_vacuum_integral,
    evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared,
    evaluate_one_loop_vakint_expression,
    loop_function,
    loop_function_pole_part,
    loop_function_to_vakint_integral,
    reduce_loop_function_first_power,
    reduce_loop_function_ibp,
    reduce_loop_functions_first_power,
    reduce_loop_functions_ibp,
    simplify_loop_functions,
)
from .indices import (
    TensorCanonicalIndex,
    TensorCanonization,
    canonize_tensor_indices,
    collect_indices,
    dummy_indices,
    open_indices,
    relabel_dummy_indices,
    tensor_index_specs,
)
from .logging import configure_logging, disable_logging, get_logger
from .matching import (
    BosonicCDEExpansionPlan,
    BosonicCDEExpansionPlanEntry,
    BosonicCDETraceExpansionTerm,
    FluctuationBasis,
    FluctuationMode,
    FluctuationOperator,
    FluctuationOperatorBlock,
    FluctuationPropagator,
    FluctuationSector,
    FluctuationStatistics,
    OneLoopMatchingNotImplementedError,
    OneLoopSetup,
    PowerTypeSupertraceContribution,
    PropagatorPlan,
    SupertraceBlockTrace,
    SupertracePlan,
    WilsonLineTracePath,
)
from .matching_options import (
    OneLoopIntegralBackend,
    OneLoopMatchOptions,
    OneLoopNormalization,
    VakintIntegralStage,
    one_loop_normalization_factor,
)
from .matching_results import (
    MatchingConditionTarget,
    MatchingExpressionComparison,
    MatchingResult,
    MatchingResultComparison,
    matching_condition_targets,
    registered_wilson_matching_condition_targets,
)
from .operator_bases import OperatorBasis, define_wilson_coefficient_from_basis
from .smeft import (
    SUPPORTED_SMEFT_WARSAW_OPERATOR_NAMES,
    define_smeft_wilson_coefficient,
    smeft_warsaw_basis,
    smeft_warsaw_operator,
    smeft_warsaw_operator_names,
)
from .state import PycheteState, StateExpression, load_state
from .symbols import SymbolDataKey, SymbolRole, canonical_string, display_string, latex_string, s
from .theory import Theory
from .theory_metadata import (
    BuiltinIndexType,
    CGTensorDefinition,
    CGTensorHandle,
    CouplingHandle,
    ExternalDefinition,
    ExternalHandle,
    ExternalKind,
    FieldChirality,
    FieldHandle,
    FieldMassKind,
    FieldRole,
    FieldVariation,
    FreeLagConvention,
    GroupKind,
    RepresentationDefinition,
    RepresentationReality,
)
from .tree_matching import HeavyScalarSolution
from .validation import (
    NumericProbePlan,
    NumericProbeResult,
    build_numeric_probe_plan,
    deterministic_probe_samples,
    evaluator_probe_equal,
)
from .validation_fixtures import (
    MatchingFixtureGapReport,
    SupertraceOrderCoverage,
    ValidationFixture,
    load_validation_fixture,
)
from .wilson_lines import expand_wilson_terms, wilson_term_expansion

__all__ = [
    "BuiltinIndexType",
    "absorb_vakint_scalar_loop_momentum_numerators",
    "BosonicCDEExpansionPlan",
    "BosonicCDEExpansionPlanEntry",
    "BosonicCDETraceExpansionTerm",
    "CGTensorDefinition",
    "CGTensorHandle",
    "CouplingHandle",
    "ExternalDefinition",
    "ExternalHandle",
    "ExternalKind",
    "FieldHandle",
    "FieldChirality",
    "FieldMassKind",
    "FieldRole",
    "FieldVariation",
    "FluctuationBasis",
    "FluctuationMode",
    "FluctuationOperator",
    "FluctuationOperatorBlock",
    "FluctuationPropagator",
    "FluctuationSector",
    "FluctuationStatistics",
    "FreeLagConvention",
    "GroupKind",
    "HeavyScalarSolution",
    "MatchingExpressionComparison",
    "MatchingConditionTarget",
    "MatchingResult",
    "MatchingResultComparison",
    "MatchingFixtureGapReport",
    "NumericProbePlan",
    "NumericProbeResult",
    "OneLoopMatchingNotImplementedError",
    "OneLoopIntegralBackend",
    "OneLoopMatchOptions",
    "OneLoopNormalization",
    "OneLoopSetup",
    "OperatorBasis",
    "PowerTypeSupertraceContribution",
    "PropagatorPlan",
    "PycheteState",
    "RepresentationDefinition",
    "RepresentationReality",
    "StateExpression",
    "SUPPORTED_SMEFT_WARSAW_OPERATOR_NAMES",
    "SupertraceOrderCoverage",
    "SupertraceBlockTrace",
    "SupertracePlan",
    "SymbolDataKey",
    "SymbolRole",
    "TensorCanonicalIndex",
    "TensorCanonization",
    "Theory",
    "ValidationFixture",
    "VakintIntegralStage",
    "canonical_string",
    "WilsonLineTracePath",
    "canonize_loop_function",
    "canonize_loop_functions",
    "canonize_tensor_indices",
    "collect_indices",
    "configure_logging",
    "display_string",
    "disable_logging",
    "dummy_indices",
    "build_numeric_probe_plan",
    "deterministic_probe_samples",
    "define_smeft_wilson_coefficient",
    "define_wilson_coefficient_from_basis",
    "evaluator_probe_equal",
    "evaluate_loop_functions",
    "evaluate_one_loop_single_scale_vakint_expression",
    "evaluate_one_loop_single_scale_vacuum_integral",
    "evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared",
    "evaluate_one_loop_vakint_expression",
    "expand_wilson_terms",
    "get_logger",
    "hermitian_conjugate",
    "infer_coupling_mass_dimensions",
    "loop_function",
    "loop_function_pole_part",
    "loop_function_to_vakint_integral",
    "load_validation_fixture",
    "load_state",
    "latex_string",
    "open_indices",
    "operator_dimension",
    "one_loop_normalization_factor",
    "matching_condition_targets",
    "reduce_loop_function_first_power",
    "reduce_loop_function_ibp",
    "reduce_loop_functions_first_power",
    "reduce_loop_functions_ibp",
    "relabel_dummy_indices",
    "registered_wilson_matching_condition_targets",
    "s",
    "series_eft",
    "smeft_warsaw_basis",
    "smeft_warsaw_operator",
    "smeft_warsaw_operator_names",
    "simplify_loop_functions",
    "simplify_pychete_color",
    "tensor_index_specs",
    "wilson_term_expansion",
]
