from __future__ import annotations

from .eft import operator_dimension, series_eft
from .backends.vacuum_integrals import (
    canonize_loop_function,
    canonize_loop_functions,
    evaluate_loop_functions,
    evaluate_one_loop_single_scale_vakint_expression,
    evaluate_one_loop_single_scale_vacuum_integral,
    evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared,
    evaluate_one_loop_vakint_expression,
    loop_function,
    loop_function_pole_part,
    loop_function_to_vakint_integral,
    reduce_loop_function_first_power,
    reduce_loop_function_ibp,
    reduce_loop_functions_first_power,
    reduce_loop_functions_ibp,
    simplify_loop_functions,
)
from .indices import collect_indices, dummy_indices, open_indices, relabel_dummy_indices
from .matching import (
    FluctuationBasis,
    FluctuationMode,
    FluctuationOperator,
    FluctuationOperatorBlock,
    FluctuationPropagator,
    FluctuationSector,
    FluctuationStatistics,
    OneLoopMatchingNotImplementedError,
    OneLoopSetup,
    PowerTypeSupertraceContribution,
    PropagatorPlan,
    SupertraceBlockTrace,
    SupertracePlan,
)
from .matching_options import (
    OneLoopIntegralBackend,
    OneLoopMatchOptions,
    OneLoopNormalization,
    VakintIntegralStage,
    one_loop_normalization_factor,
)
from .matching_results import MatchingExpressionComparison, MatchingResult, MatchingResultComparison
from .state import PycheteState, StateExpression, load_state
from .symbols import SymbolDataKey, SymbolRole, canonical_string, display_string, latex_string, s
from .theory import Theory
from .theory_metadata import (
    BuiltinIndexType,
    CGTensorDefinition,
    CGTensorHandle,
    CouplingHandle,
    ExternalDefinition,
    ExternalHandle,
    ExternalKind,
    FieldChirality,
    FieldHandle,
    FieldMassKind,
    FieldRole,
    FieldVariation,
    GroupKind,
    RepresentationDefinition,
    RepresentationReality,
)
from .tree_matching import HeavyScalarSolution
from .validation import (
    NumericProbePlan,
    NumericProbeResult,
    build_numeric_probe_plan,
    deterministic_probe_samples,
    evaluator_probe_equal,
)

__all__ = [
    "BuiltinIndexType",
    "CGTensorDefinition",
    "CGTensorHandle",
    "CouplingHandle",
    "ExternalDefinition",
    "ExternalHandle",
    "ExternalKind",
    "FieldHandle",
    "FieldChirality",
    "FieldMassKind",
    "FieldRole",
    "FieldVariation",
    "FluctuationBasis",
    "FluctuationMode",
    "FluctuationOperator",
    "FluctuationOperatorBlock",
    "FluctuationPropagator",
    "FluctuationSector",
    "FluctuationStatistics",
    "GroupKind",
    "HeavyScalarSolution",
    "MatchingExpressionComparison",
    "MatchingResult",
    "MatchingResultComparison",
    "NumericProbePlan",
    "NumericProbeResult",
    "OneLoopMatchingNotImplementedError",
    "OneLoopIntegralBackend",
    "OneLoopMatchOptions",
    "OneLoopNormalization",
    "OneLoopSetup",
    "PowerTypeSupertraceContribution",
    "PropagatorPlan",
    "PycheteState",
    "RepresentationDefinition",
    "RepresentationReality",
    "StateExpression",
    "SupertraceBlockTrace",
    "SupertracePlan",
    "SymbolDataKey",
    "SymbolRole",
    "Theory",
    "VakintIntegralStage",
    "canonical_string",
    "canonize_loop_function",
    "canonize_loop_functions",
    "collect_indices",
    "display_string",
    "dummy_indices",
    "build_numeric_probe_plan",
    "deterministic_probe_samples",
    "evaluator_probe_equal",
    "evaluate_loop_functions",
    "evaluate_one_loop_single_scale_vakint_expression",
    "evaluate_one_loop_single_scale_vacuum_integral",
    "evaluate_one_loop_single_scale_vacuum_integral_from_mass_squared",
    "evaluate_one_loop_vakint_expression",
    "loop_function",
    "loop_function_pole_part",
    "loop_function_to_vakint_integral",
    "load_state",
    "latex_string",
    "open_indices",
    "operator_dimension",
    "one_loop_normalization_factor",
    "reduce_loop_function_first_power",
    "reduce_loop_function_ibp",
    "reduce_loop_functions_first_power",
    "reduce_loop_functions_ibp",
    "relabel_dummy_indices",
    "s",
    "series_eft",
    "simplify_loop_functions",
]
